config/routes.rb
Rails.application.routes.draw do
  resources :gestao_beneficios
  resources :automacao_tarefas
  resources :projetos
  resources :relatorios
  resources :cadastro_ativos
  resources :ponto_eletronicos
  resources :processo_admissaos
  resources :folha_pagamentos
  resources :pedido_vendas
  resources :consulta_estoques
  resources :fornecedors
  resources :pedido_compras
  resources :ordem_pagamentos
  resources :gerenciamento_contas_bancaria
  resources :titulos_baixados
  resources :titulos_em_abertos
  resources :tesouraria
  resources :fluxo_caixas
  resources :conta_recebers
  resources :conta_pagars
  resources :compras
  resources :departamentos
  root 'home#index'
  

  devise_for :users

  resources :products do
    collection do
      get 'search'  # Definido o caminho para a pesquisa de produtos
    end
  end

  resources :clients
  resources :vendas
  resources :servicos
  resources :funcionarios
  resources :automacao_tarefas

  get 'home/index', as: 'home_index'
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :vendas

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true
end

app/models/compra.rb
class Compra < ApplicationRecord
end

app/models/conta_pagar.rb
class ContaPagar < ApplicationRecord
end

app/models/conta_receber.rb
class ContaReceber < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/fluxo_caixa.rb
class FluxoCaixa < ApplicationRecord
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

app/models/order_item.rb
# app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :venda
  belongs_to :product

  validates :product_id, presence: true
  validates :quantidade, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/pedido_compra.rb
class PedidoCompra < ApplicationRecord
end

app/models/pedido_venda.rb
class PedidoVenda < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :vendas
  has_many :order_items
end

app/models/projeto.rb
class Projeto < ApplicationRecord
end

app/models/relatorio.rb
class Relatorio < ApplicationRecord
end

app/models/servico.rb
class Servico < ApplicationRecord
end

app/models/tesourarium.rb
class Tesourarium < ApplicationRecord
end

app/models/titulos_em_aberto.rb
class TitulosEmAberto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venda.rb
class Venda < ApplicationRecord
  has_many :order_items
  accepts_nested_attributes_for :order_items
  has_many :order_items, dependent: :destroy

  validates :funcionario_id, :client_id, :data, presence: true
end

class OrderItem < ApplicationRecord
  belongs_to :venda
  belongs_to :product

  validates :product_id, :quantidade, presence: true
end

app/controllers/titulos_em_abertos_controller.rb
class TitulosEmAbertosController < ApplicationController
  before_action :set_titulos_em_aberto, only: %i[ show edit update destroy ]

  # GET /titulos_em_abertos or /titulos_em_abertos.json
  def index
    @titulos_em_abertos = TitulosEmAberto.all
  end

  # GET /titulos_em_abertos/1 or /titulos_em_abertos/1.json
  def show
  end

  # GET /titulos_em_abertos/new
  def new
    @titulos_em_aberto = TitulosEmAberto.new
  end

  # GET /titulos_em_abertos/1/edit
  def edit
  end

  # POST /titulos_em_abertos or /titulos_em_abertos.json
  def create
    @titulos_em_aberto = TitulosEmAberto.new(titulos_em_aberto_params)

    respond_to do |format|
      if @titulos_em_aberto.save
        format.html { redirect_to titulos_em_aberto_url(@titulos_em_aberto), notice: "Titulos em aberto was successfully created." }
        format.json { render :show, status: :created, location: @titulos_em_aberto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @titulos_em_aberto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titulos_em_abertos/1 or /titulos_em_abertos/1.json
  def update
    respond_to do |format|
      if @titulos_em_aberto.update(titulos_em_aberto_params)
        format.html { redirect_to titulos_em_aberto_url(@titulos_em_aberto), notice: "Titulos em aberto was successfully updated." }
        format.json { render :show, status: :ok, location: @titulos_em_aberto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @titulos_em_aberto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titulos_em_abertos/1 or /titulos_em_abertos/1.json
  def destroy
    @titulos_em_aberto.destroy!

    respond_to do |format|
      format.html { redirect_to titulos_em_abertos_url, notice: "Titulos em aberto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_titulos_em_aberto
      @titulos_em_aberto = TitulosEmAberto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def titulos_em_aberto_params
      params.require(:titulos_em_aberto).permit(:cliente, :data_vencimento, :valor, :descricao, :status)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/titulos_em_abertos_helper.rb
module TitulosEmAbertosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/titulos_em_abertos/_form.html.erb
<%= form_with(model: titulos_em_aberto) do |form| %>
  <% if titulos_em_aberto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(titulos_em_aberto.errors.count, "error") %> prohibited this titulos_em_aberto from being saved:</h2>

      <ul>
        <% titulos_em_aberto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cliente, style: "display: block" %>
    <%= form.text_field :cliente %>
  </div>

  <div>
    <%= form.label :data_vencimento, style: "display: block" %>
    <%= form.date_field :data_vencimento %>
  </div>

  <div>
    <%= form.label :valor, style: "display: block" %>
    <%= form.text_field :valor %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/titulos_em_abertos/_titulos_em_aberto.html.erb
<div id="<%= dom_id titulos_em_aberto %>">
  <p>
    <strong>Cliente:</strong>
    <%= titulos_em_aberto.cliente %>
  </p>

  <p>
    <strong>Data vencimento:</strong>
    <%= titulos_em_aberto.data_vencimento %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= titulos_em_aberto.valor %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= titulos_em_aberto.descricao %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= titulos_em_aberto.status %>
  </p>

</div>

app/views/titulos_em_abertos/edit.html.erb
<% content_for :title, "Editing titulos em aberto" %>

<h1>Editing titulos em aberto</h1>

<%= render "form", titulos_em_aberto: @titulos_em_aberto %>

<br>

<div>
  <%= link_to "Show this titulos em aberto", @titulos_em_aberto %> |
  <%= link_to "Back to titulos em abertos", titulos_em_abertos_path %>
</div>

app/views/titulos_em_abertos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Titulos em abertos" %>

<h1>Titulos em abertos</h1>

<div id="titulos_em_abertos">
  <% @titulos_em_abertos.each do |titulos_em_aberto| %>
    <%= render titulos_em_aberto %>
    <p>
      <%= link_to "Show this titulos em aberto", titulos_em_aberto %>
    </p>
  <% end %>
</div>

<%= link_to "New titulos em aberto", new_titulos_em_aberto_path %>

app/views/titulos_em_abertos/new.html.erb
<% content_for :title, "New titulos em aberto" %>

<h1>New titulos em aberto</h1>

<%= render "form", titulos_em_aberto: @titulos_em_aberto %>

<br>

<div>
  <%= link_to "Back to titulos em abertos", titulos_em_abertos_path %>
</div>

app/views/titulos_em_abertos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @titulos_em_aberto %>

<div>
  <%= link_to "Edit this titulos em aberto", edit_titulos_em_aberto_path(@titulos_em_aberto) %> |
  <%= link_to "Back to titulos em abertos", titulos_em_abertos_path %>

  <%= button_to "Destroy this titulos em aberto", @titulos_em_aberto, method: :delete %>
</div>