config/routes.rb
Rails.application.routes.draw do
  resources :gestao_beneficios
  resources :automacao_tarefas
  resources :projetos
  resources :relatorios
  resources :cadastro_ativos
  resources :ponto_eletronicos
  resources :processo_admissaos
  resources :folha_pagamentos
  resources :pedido_vendas
  resources :consulta_estoques
  resources :fornecedors
  resources :pedido_compras
  resources :ordem_pagamentos
  resources :gerenciamento_contas_bancaria
  resources :titulos_baixados
  resources :titulos_em_abertos
  resources :tesouraria
  resources :fluxo_caixas
  resources :conta_recebers
  resources :conta_pagars
  resources :compras
  resources :departamentos
  root 'home#index'
  

  devise_for :users

  resources :products do
    collection do
      get 'search'  # Definido o caminho para a pesquisa de produtos
    end
  end

  resources :clients
  resources :vendas
  resources :servicos
  resources :funcionarios
  resources :automacao_tarefas

  get 'home/index', as: 'home_index'
end

app/models/automacao_tarefa.rb
class AutomacaoTarefa < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :vendas

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true
end

app/models/compra.rb
class Compra < ApplicationRecord
end

app/models/conta_pagar.rb
class ContaPagar < ApplicationRecord
end

app/models/conta_receber.rb
class ContaReceber < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/fluxo_caixa.rb
class FluxoCaixa < ApplicationRecord
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

app/models/order_item.rb
# app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :venda
  belongs_to :product

  validates :product_id, presence: true
  validates :quantidade, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/pedido_compra.rb
class PedidoCompra < ApplicationRecord
end

app/models/pedido_venda.rb
class PedidoVenda < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :vendas
  has_many :order_items
end

app/models/projeto.rb
class Projeto < ApplicationRecord
end

app/models/relatorio.rb
class Relatorio < ApplicationRecord
end

app/models/servico.rb
class Servico < ApplicationRecord
end

app/models/tesourarium.rb
class Tesourarium < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venda.rb
class Venda < ApplicationRecord
  has_many :order_items
  accepts_nested_attributes_for :order_items
  has_many :order_items, dependent: :destroy

  validates :funcionario_id, :client_id, :data, presence: true
end

class OrderItem < ApplicationRecord
  belongs_to :venda
  belongs_to :product

  validates :product_id, :quantidade, presence: true
end

app/controllers/automacao_tarefas_controller.rb
class AutomacaoTarefasController < ApplicationController
  before_action :set_automacao_tarefa, only: %i[ show edit update destroy ]

  # GET /automacao_tarefas or /automacao_tarefas.json
  def index
    @automacao_tarefas = AutomacaoTarefa.all
  end

  # GET /automacao_tarefas/1 or /automacao_tarefas/1.json
  def show
  end

  # GET /automacao_tarefas/new
  def new
    @automacao_tarefa = AutomacaoTarefa.new
  end

  # GET /automacao_tarefas/1/edit
  def edit
  end

  # POST /automacao_tarefas or /automacao_tarefas.json
  def create
    @automacao_tarefa = AutomacaoTarefa.new(automacao_tarefa_params)

    respond_to do |format|
      if @automacao_tarefa.save
        format.html { redirect_to automacao_tarefa_url(@automacao_tarefa), notice: "Automacao tarefa was successfully created." }
        format.json { render :show, status: :created, location: @automacao_tarefa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @automacao_tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /automacao_tarefas/1 or /automacao_tarefas/1.json
  def update
    respond_to do |format|
      if @automacao_tarefa.update(automacao_tarefa_params)
        format.html { redirect_to automacao_tarefa_url(@automacao_tarefa), notice: "Automacao tarefa was successfully updated." }
        format.json { render :show, status: :ok, location: @automacao_tarefa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @automacao_tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /automacao_tarefas/1 or /automacao_tarefas/1.json
  def destroy
    @automacao_tarefa.destroy!

    respond_to do |format|
      format.html { redirect_to automacao_tarefas_url, notice: "Automacao tarefa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_automacao_tarefa
      @automacao_tarefa = AutomacaoTarefa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def automacao_tarefa_params
      params.require(:automacao_tarefa).permit(:nome, :descricao, :horario, :frequencia, :ativo)
    end
end

app/helpers/automacao_tarefas_helper.rb
module AutomacaoTarefasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/automacao_tarefas/_automacao_tarefa.html.erb
<div id="<%= dom_id automacao_tarefa %>">
  <p>
    <strong>Nome:</strong>
    <%= automacao_tarefa.nome %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= automacao_tarefa.descricao %>
  </p>

  <p>
    <strong>Horario:</strong>
    <%= automacao_tarefa.horario %>
  </p>

  <p>
    <strong>Frequencia:</strong>
    <%= automacao_tarefa.frequencia %>
  </p>

  <p>
    <strong>Ativo:</strong>
    <%= automacao_tarefa.ativo %>
  </p>

</div>

app/views/automacao_tarefas/_form.html.erb
<%= form_with(model: automacao_tarefa) do |form| %>
  <% if automacao_tarefa.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(automacao_tarefa.errors.count, "error") %> prohibited this automacao_tarefa from being saved:</h2>

      <ul>
        <% automacao_tarefa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.label :horario, style: "display: block" %>
    <%= form.time_field :horario %>
  </div>

  <div>
    <%= form.label :frequencia, style: "display: block" %>
    <%= form.text_field :frequencia %>
  </div>

  <div>
    <%= form.label :ativo, style: "display: block" %>
    <%= form.check_box :ativo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/automacao_tarefas/edit.html.erb
<% content_for :title, "Editing automacao tarefa" %>

<h1>Editing automacao tarefa</h1>

<%= render "form", automacao_tarefa: @automacao_tarefa %>

<br>

<div>
  <%= link_to "Show this automacao tarefa", @automacao_tarefa %> |
  <%= link_to "Back to automacao tarefas", automacao_tarefas_path %>
</div>

app/views/automacao_tarefas/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Automacao tarefas" %>

<h1>Automacao tarefas</h1>

<div id="automacao_tarefas">
  <% @automacao_tarefas.each do |automacao_tarefa| %>
    <%= render automacao_tarefa %>
    <p>
      <%= link_to "Show this automacao tarefa", automacao_tarefa %>
    </p>
  <% end %>
</div>

<%= link_to "New automacao tarefa", new_automacao_tarefa_path %>

app/views/automacao_tarefas/new.html.erb
<% content_for :title, "New automacao tarefa" %>

<h1>New automacao tarefa</h1>

<%= render "form", automacao_tarefa: @automacao_tarefa %>

<br>

<div>
  <%= link_to "Back to automacao tarefas", automacao_tarefas_path %>
</div>

app/views/automacao_tarefas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @automacao_tarefa %>

<div>
  <%= link_to "Edit this automacao tarefa", edit_automacao_tarefa_path(@automacao_tarefa) %> |
  <%= link_to "Back to automacao tarefas", automacao_tarefas_path %>

  <%= button_to "Destroy this automacao tarefa", @automacao_tarefa, method: :delete %>
</div>