config/routes.rb
Rails.application.routes.draw do
  resources :gestao_beneficios
  resources :automacao_tarefas
  resources :projetos
  resources :relatorios
  resources :cadastro_ativos
  resources :ponto_eletronicos
  resources :processo_admissaos
  resources :folha_pagamentos
  resources :pedido_vendas
  resources :consulta_estoques
  resources :fornecedors
  resources :pedido_compras
  resources :ordem_pagamentos
  resources :gerenciamento_contas_bancaria
  resources :titulos_baixados
  resources :titulos_em_abertos
  resources :tesouraria
  resources :fluxo_caixas
  resources :conta_recebers
  resources :conta_pagars
  resources :compras
  resources :departamentos
  root 'home#index'
  

  devise_for :users

  resources :products do
    collection do
      get 'search'  # Definido o caminho para a pesquisa de produtos
    end
  end

  resources :clients
  resources :vendas
  resources :servicos
  resources :funcionarios
  resources :automacao_tarefas

  get 'home/index', as: 'home_index'
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :vendas

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true
end

app/models/compra.rb
class Compra < ApplicationRecord
end

app/models/conta_pagar.rb
class ContaPagar < ApplicationRecord
end

app/models/conta_receber.rb
class ContaReceber < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/fluxo_caixa.rb
class FluxoCaixa < ApplicationRecord
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

app/models/order_item.rb
# app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :venda
  belongs_to :product

  validates :product_id, presence: true
  validates :quantidade, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/pedido_compra.rb
class PedidoCompra < ApplicationRecord
end

app/models/pedido_venda.rb
class PedidoVenda < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :vendas
  has_many :order_items
end

app/models/projeto.rb
class Projeto < ApplicationRecord
end

app/models/relatorio.rb
class Relatorio < ApplicationRecord
end

app/models/servico.rb
class Servico < ApplicationRecord
end

app/models/tesourarium.rb
class Tesourarium < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venda.rb
class Venda < ApplicationRecord
  has_many :order_items
  accepts_nested_attributes_for :order_items
  has_many :order_items, dependent: :destroy

  validates :funcionario_id, :client_id, :data, presence: true
end

class OrderItem < ApplicationRecord
  belongs_to :venda
  belongs_to :product

  validates :product_id, :quantidade, presence: true
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[ show edit update destroy ]

  # GET /funcionarios or /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1 or /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios or /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario was successfully created." }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1 or /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario was successfully updated." }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1 or /funcionarios/1.json
  def destroy
    @funcionario.destroy!

    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: "Funcionario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf, :data_nascimento, :endereco, :telefone, :email, :cargo, :salario, :data_admissao, :ativo, :departamento, :genero, :estado_civil, :identificacao)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario) do |form| %>
  <% if funcionario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
        <% funcionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :data_nascimento, style: "display: block" %>
    <%= form.date_field :data_nascimento %>
  </div>

  <div>
    <%= form.label :endereco, style: "display: block" %>
    <%= form.text_field :endereco %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :cargo, style: "display: block" %>
    <%= form.text_field :cargo %>
  </div>

  <div>
    <%= form.label :salario, style: "display: block" %>
    <%= form.text_field :salario %>
  </div>

  <div>
    <%= form.label :data_admissao, style: "display: block" %>
    <%= form.date_field :data_admissao %>
  </div>

  <div>
    <%= form.label :ativo, style: "display: block" %>
    <%= form.check_box :ativo %>
  </div>

  <div>
    <%= form.label :departamento, style: "display: block" %>
    <%= form.text_field :departamento %>
  </div>

  <div>
    <%= form.label :genero, style: "display: block" %>
    <%= form.text_field :genero %>
  </div>

  <div>
    <%= form.label :estado_civil, style: "display: block" %>
    <%= form.text_field :estado_civil %>
  </div>

  <div>
    <%= form.label :identificacao, style: "display: block" %>
    <%= form.text_field :identificacao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/funcionarios/_funcionario.html.erb
<div id="<%= dom_id funcionario %>">
  <p>
    <strong>Nome:</strong>
    <%= funcionario.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= funcionario.cpf %>
  </p>

  <p>
    <strong>Data nascimento:</strong>
    <%= funcionario.data_nascimento %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= funcionario.endereco %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= funcionario.telefone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= funcionario.email %>
  </p>

  <p>
    <strong>Cargo:</strong>
    <%= funcionario.cargo %>
  </p>

  <p>
    <strong>Salario:</strong>
    <%= funcionario.salario %>
  </p>

  <p>
    <strong>Data admissao:</strong>
    <%= funcionario.data_admissao %>
  </p>

  <p>
    <strong>Ativo:</strong>
    <%= funcionario.ativo %>
  </p>

  <p>
    <strong>Departamento:</strong>
    <%= funcionario.departamento %>
  </p>

  <p>
    <strong>Genero:</strong>
    <%= funcionario.genero %>
  </p>

  <p>
    <strong>Estado civil:</strong>
    <%= funcionario.estado_civil %>
  </p>

  <p>
    <strong>Identificacao:</strong>
    <%= funcionario.identificacao %>
  </p>

</div>

app/views/funcionarios/edit.html.erb
<% content_for :title, "Editing funcionario" %>

<h1>Editing funcionario</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Show this funcionario", @funcionario %> |
  <%= link_to "Back to funcionarios", funcionarios_path %>
</div>

app/views/funcionarios/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Incluir a biblioteca jQuery -->
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  <!-- Incluir a folha de estilo Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>

  <!-- Incluir a folha de estilo específica da view -->
  <%= stylesheet_link_tag 'https://cdn.datatables.net/1.11.6/css/dataTables.bootstrap.min.css' %>
  <%= stylesheet_link_tag 'vendas/vendas.css', media: 'all' %>

  <!-- Carregar o arquivo JavaScript para alternância de tema -->
  <%= javascript_include_tag 'application' %>

  <!-- Adicionar DataTables -->
  <%= javascript_include_tag 'https://cdn.datatables.net/1.11.6/js/jquery.dataTables.min.js' %>
  <%= javascript_include_tag 'https://cdn.datatables.net/1.11.6/js/dataTables.bootstrap.min.js' %>

  <!-- Incluir a biblioteca do Google Charts -->
  <%= javascript_include_tag "//www.gstatic.com/charts/loader.js" %>
</head>

<body class="chart-grid">
  <div class="page-border">

    <!-- Mensagem de aviso -->
    <p style="color: green"><%= notice %></p>

    <!-- Título da página -->
    <% content_for :title, "Funcionarios" %>

    <div class="titulo-da-pagina">
      <h1>Funcionarios cadastrados</h1>
    </div>

    <!-- Link para adicionar novo funcionário -->
    <%= link_to "New funcionario", new_funcionario_path %>

    <!-- Tabela de funcionários -->
    <table id="tabela-vendas" class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>CPF</th>
          <th>Endereço</th>
          <th>Telefone</th>
          <th>Cargo</th>
          <th>Salário</th>
          <th>Data de Admissão</th>
          <th>Departamento</th>
          <th>Estado Civil</th>
        </tr>
      </thead>
      <tbody>
        <% @funcionarios.each do |funcionario| %>
          <tr>
            <td><%= link_to funcionario.id, funcionario_path(funcionario) %></td>
            <td><%= funcionario.nome %></td>
            <td><%= funcionario.cpf %></td>
            <td><%= funcionario.endereco %></td>
            <td><%= funcionario.telefone %></td>
            <td><%= funcionario.cargo %></td>
            <td><%= funcionario.salario %></td>
            <td><%= funcionario.data_admissao %></td>
            <td><%= funcionario.departamento %></td>
            <td><%= funcionario.estado_civil %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!-- Script para inicializar DataTables -->
    <script>
      $(document).ready(function() {
        $('#tabela-vendas').DataTable({
          "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
          "pageLength": 10
        });
      });
    </script>
  </div>
</body>
</html>

app/views/funcionarios/new.html.erb
<% content_for :title, "New funcionario" %>

<h1>New funcionario</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Back to funcionarios", funcionarios_path %>
</div>

app/views/funcionarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @funcionario %>

<div>
  <%= link_to "Edit this funcionario", edit_funcionario_path(@funcionario) %> |
  <%= link_to "Back to funcionarios", funcionarios_path %>

  <%= button_to "Destroy this funcionario", @funcionario, method: :delete %>
</div>